name: 'complexity_perspective'
version: 0.0.1
description: Source code for the book "Die ‚komplexe‘ Perspektive - Einführung in die digitale Wirtschaft".
author: Jörn Dinkla <joern@dinkla.net>
homepage: https://complex-perspective.dinkla.net

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0